openapi: 3.1.0
info:
  title: NeetoForm APIs
  description: ''
  version: 1.0.0
tags:
  - name: Forms
  - name: Submissions
paths:
  /api/external/v1/forms:
    get:
      summary: List all forms
      deprecated: false
      description: >
        This API allows to list all the forms in a workspace. Replace `workspace-name`
        with your workspace's subdomain.
      tags:
        - Forms
      parameters:
        - name: page_number
          in: query
          description: >-
            Retrieve paginated forms by specifying the desired page number. If
            this parameter is absent, all forms will be returned.
          required: false
          schema:
            type: Number
        - name: page_size
          in: query
          description: >-
            Set the number of results returned in the response. Defaulting to 30
            when omitted.
          required: false
          schema:
            type: Number
      responses:
        '200':
          description: OK - Request succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  forms:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        is_published:
                          type: boolean
                        state:
                          type: string
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
                        submissions_count:
                          type: integer
                        attempt_url:
                          type: string
                        is_archived:
                          type: boolean
                        is_disabled:
                          type: boolean
                        is_suspended:
                          type: boolean
                        created_by:
                          type: string
                  total_count:
                    type: integer
          headers: {}
      security:
        - apikey-header-X-Api-Key: []
  /api/external/v1/forms/{form_id}/submissions:
    get:
      summary: List all submissions
      deprecated: false
      description: >-
        This API allows to list all the submissions of a specified form in a
        workspace. Replace `workspace-name` with your workspace's subdomain.
      tags:
        - Submissions
      parameters:
        - name: form_id
          in: path
          description: >-
            Id of the form can be retrieved by going to the particular form, and
            copying it from the URL.
          required: true
          example: 238c77e9-f9b5-4cf7-b15a-a16b703ff4d6
          schema:
            type: string
        - name: page_number
          in: query
          description: >-
            Retrieve paginated.
          required: false
          schema:
            type: Number
        - name: page_size
          in: query
          description: >-
            Set the number of results returned in the response. Defaulting to 30
            when omitted.
          required: false
          schema:
            type: Number
      responses:
        '200':
          description: OK - Request succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  submissions:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        created_at:
                          type: string
                          format: date-time
                        field_values:
                          type: array
                          items:
                            type: object
                            properties: {}
                        user_agent:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                            version:
                              type: string
                            ip_address:
                              type: string
                            device_name:
                              type: string
                            device_type:
                              type: string
                            operating_system:
                              type: string
                            operating_system_version:
                              type: string
                            submission_id:
                              type: string
                            created_at:
                              type: string
                              format: date-time
                            updated_at:
                              type: string
                              format: date-time
                        responses:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: string
                              label:
                                type: string
                              position:
                                type: integer
                              kind:
                                type: string
                              slug:
                                type: string
                              value:
                                type: string
                  total_count:
                    type: integer
          headers: {}
      security:
        - apikey-header-X-Api-Key: []

webhooks: {}
components:
  securitySchemes:
    apikey-header-X-Api-Key:
      type: apiKey
      in: header
      name: X-Api-Key
servers: []
security:
  - apikey-header-X-Api-Key: []
